#!/bin/sh
SUDO_ASKPASS='/usr/bin/ksshaskpass'

if test -e "$HOME"/.config/azurite/firstboot-done; then
    echo "User Setup is already done."
    exit 0
fi

echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Removing Filtered Flathub Repo Failed"
        exit 1
fi

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Adding Flathub Repo Failed"
        exit 1
fi

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Removing all preinstalled flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Removing Fedora Flatpak Repo Failed"
        exit 1
fi

echo "# Installing Steam"
/usr/bin/flatpak install --user --or-update --noninteractive flathub com.valvesoftware.Steam
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Steam Failed"
        exit 1
fi

echo "# Installing Heroic Launcher"
/usr/bin/flatpak install --user --or-update --noninteractive flathub com.heroicgameslauncher.hgl
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Heroic Failed"
        exit 1
fi

echo "# Installing Synology Drive Client"
/usr/bin/flatpak install --user --or-update --noninteractive flathub com.synology.SynologyDrive
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Synology Drive Failed"
        exit 1
fi

echo "# Installing Digikam"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.digikam
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Digikam Failed"
        exit 1
fi

echo "# Installing Krita"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.krita
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Krita Failed"
        exit 1
fi

echo "# Installing Neochat"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.neochat
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Neochat Failed"
        exit 1
fi

echo "# Installing Kate"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.kate
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Kate Failed"
        exit 1
fi

echo "# Installing Elisa"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.elisa
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Elisa Failed"
        exit 1
fi

echo "# Installing Kcalc"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.kde.kcalc
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Kcalc Failed"
        exit 1
fi

echo "# Installing Virt-Manager"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.virt_manager.virt-manager
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.virt_manager.virt_manager.Extension.Qemu
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Virt Manager Failed"
        exit 1
fi

echo "# Installing Firefox"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Firefox Failed"
        exit 1
fi

echo "# Installing Thunderbird"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.mozilla.thunderbird
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Thunderbird Failed"
        exit 1
fi

echo "# Installing Libreoffice"
/usr/bin/flatpak install --user --or-update --noninteractive flathub org.libreoffice.LibreOffice
if [ "$?" != 0 ] ; then
        kdialog --error \
          "Installing Thunderbird Failed"
        exit 1
fi

mkdir -p "$HOME"/.config/azurite/
touch "$HOME"/.config/azurite/firstboot-done