ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-41}"

## Begin with a Kinoite Base Image
FROM quay.io/fedora-ostree-desktops/kinoite:${FEDORA_MAJOR_VERSION}

ARG OS_VERSION="${OS_VERSION:-${FEDORA_MAJOR_VERSION}}"

COPY os-release/os-release-template /etc/os-release
RUN sed -i 's/FEDORA_VERSION/'"${OS_VERSION}"'/g' /etc/os-release
COPY etc /etc
COPY usr /usr
COPY azurite-first-setup /usr/bin

#Clean up packages to use the ones I want.
RUN rpm-ostree override remove \
        plasma-discover-rpm-ostree \
        toolbox \
        mesa-va-drivers \
        ffmpeg-free

#Add rpm fusion packages
RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#Swap libavcodec
RUN rpm-ostree remove libavcodec-free --install libavcodec-freeworld

#Add other codecs       
RUN rpm-ostree install \
        ffmpeg \
        mesa-va-drivers-freeworld \
        mesa-vdpau-drivers-freeworld \
        libheif-freeworld


#Add extra core packages
RUN  rpm-ostree install \
        distrobox \
        rsms-inter-fonts \
        libvirt-daemon-config-network \
        libvirt-daemon-kvm \
        fish \
        qemu-kvm \ 
        virt-manager \
        ksshaskpass \
        corectrl

#Add Apps that have to be layered to work well, or that I prefer to be layerd. LO is in here because I prefer the KDE dialogs, which you don't get in flatpak.
RUN rpm-ostree install \
        libreoffice \
        vorta \
        borgbackup \
        thunderbird

#Setup auto updates
RUN sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf && \
    systemctl enable rpm-ostreed-automatic.timer && \
    systemctl enable swtpm-workaround && \
    rm -rf \
        /tmp/* \
        /var/*

RUN ostree container commit