ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-41}"

## Begin with a Kinoite Base Image
FROM quay.io/fedora/fedora-kinoite:${FEDORA_MAJOR_VERSION}

ARG OS_VERSION="${OS_VERSION:-${FEDORA_MAJOR_VERSION}}"

COPY os-release/os-release-template /etc/os-release
RUN sed -i 's/FEDORA_VERSION/'"${OS_VERSION}"'/g' /etc/os-release
COPY etc /etc
COPY usr /usr
COPY azurite-first-setup /usr/bin

#Clean up packages to use the ones I want.
RUN rpm-ostree override remove \
        plasma-discover-rpm-ostree \
        toolbox \
        mesa-va-drivers \
        ffmpeg-free \
        firefox

#Add extra core packages
RUN  rpm-ostree install \
        distrobox \
        rsms-inter-fonts \
        libvirt-daemon-config-network \
        libvirt-daemon-kvm \
        swtpm-selinux \
        fish \
        qemu-kvm \ 
        virt-manager \
        ksshaskpass

#Add KDE Apps and apps that have to be layered to work well, or that I prefer to be layerd. LO is in here because I prefer the KDE dialogs, which you don't get in flatpak.
RUN rpm-ostree install \
        vorta \
        borgbackup \
        logiops \
        solaar \
        kgpg \
        kmail \
        kaddressbook \
        korganizer \
        merkuro \
        plasma-firewall-firewalld

#Setup auto updates
RUN sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf && \
    systemctl enable rpm-ostreed-automatic.timer && \
    systemctl enable swtpm-workaround && \
    rm -rf \
        /tmp/* \
        /var/*

RUN ostree container commit