ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION:-41}"

## Begin with a Kinoite Base Image
FROM quay.io/fedora/fedora-kinoite:${FEDORA_MAJOR_VERSION}

COPY etc /etc
COPY usr /usr
COPY azurite-first-setup /usr/bin

#Clean up packages to use the ones I want. Set automated staged updates.
RUN rpm-ostree override remove \
        firefox \
        firefox-langpacks \
        plasma-discover-rpm-ostree

#Add extra packages
RUN  rpm-ostree install \
        distrobox \
        rsms-inter-fonts \
        libvirt-daemon-config-network \
        libvirt-daemon-kvm \
        qemu-kvm \ 
        virt-manager \
        ksshaskpass \
        kmail \
        akonadi \
        digikam \
        krita \
        neochat \
        skanpage \
        corectrl

#Add RPMFusion packages and setup auto updates
RUN sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf && \
    systemctl enable rpm-ostreed-automatic.timer && \
    systemctl enable swtpm-workaround && \
    rm -rf \
        /tmp/* \
        /var/*

RUN ostree container commit