name: Build Azurite Image for Kinoite 41
on: 
  schedule:
    - cron: '00 12 * * *'
  push:
    paths-ignore:
      - '*.md'
  pull_request:
  workflow_dispatch:

jobs:
  run-build:
    strategy:
      matrix:
        fedora_version: [41]
    name: Run
    secrets: inherit
    uses: ./.github/workflows/main.yml
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      fedora_version: 41
      is_stable: true